name: omnisci-dev
channels:
- conda-forge
- defaults
dependencies:
- thrift=0.11.0
- numpydoc
- "pyarrow>=0.10.0,<0.12"
- arrow-cpp
- sqlalchemy
- numpy>=1.14
- pandas
- coverage
- flake8
- "pytest>=3.6,<4.0"
- pytest-cov
- pytest-mock
- mock
