name: omnisci-dev
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- six>=1.10.0
- thrift=0.11.0
- numpydoc
- pyarrow=0.10.0
- arrow-cpp=0.10.0
- sqlalchemy
- cython
- numpy>=1.14
- pandas
