name: omnisci-gpu-dev
channels:
- conda-forge
- defaults
- nvidia
- rapidsai
dependencies:
- thrift=0.13.0
- cudf=0.15
- cudatoolkit=11.0
- python >=3.7.0,<3.9
- pyarrow<=2.0
- pandas
# related: https://github.com/conda-forge/pillow-feedstock/issues/73
- libtiff=4.0.10
- geopandas
- shapely
- sqlalchemy
- numpy
- numpydoc
- coverage
- flake8
- pre-commit
- pytest-cov
- pytest-mock
- sphinx
- sphinx_rtd_theme
- requests
- rbc>=0.2.2
